"""Shared proposal-search methods used across LDM tasks."""

from __future__ import annotations

from collections.abc import Awaitable, Callable
from typing import Any

from ldm_tts.search_methods import beam_search, best_of_n, mcts, single_turn, tree_search
from ldm_tts.search_methods.protocols import (
    SearchEngine,
    SearchState,
    SearchTraversalResult,
    StateT,
)
from ldm_tts.search_methods.traversal import (
    beam_search as traverse_beam_search,
    best_of_n as traverse_best_of_n,
    estimate_beam_generated,
    estimate_tree_generated,
    single_turn as traverse_single_turn,
    tree_search as traverse_tree_search,
)


SEARCH_METHOD_ALIASES = {
    "single": "single_turn",
    "single_turn": "single_turn",
    "best_of_n": "best_of_n",
    "beam": "beam_search",
    "beam_search": "beam_search",
    "mcts": "mcts",
    "tree": "tree_search",
    "tree_search": "tree_search",
}

SEARCH_METHODS: dict[str, Callable[..., Awaitable[Any]]] = {
    "single_turn": single_turn.run,
    "best_of_n": best_of_n.run,
    "beam_search": beam_search.run,
    "mcts": mcts.run,
    "tree_search": tree_search.run,
}

TRAVERSAL_METHODS = {
    "single_turn": traverse_single_turn,
    "best_of_n": traverse_best_of_n,
    "beam_search": traverse_beam_search,
    "tree_search": traverse_tree_search,
}


def canonical_search_method(name: str) -> str:
    """Resolve a public search-method name or alias to its canonical name."""

    normalized = str(name).strip().lower()
    try:
        return SEARCH_METHOD_ALIASES[normalized]
    except KeyError as exc:
        choices = ", ".join(sorted(SEARCH_METHOD_ALIASES))
        raise ValueError(f"Unknown search method {name!r}; choose one of: {choices}") from exc


def get_search_method(name: str) -> Callable[..., Awaitable[Any]]:
    """Return the runtime implementation for a public search-method name."""

    return SEARCH_METHODS[canonical_search_method(name)]


def get_traversal_method(name: str) -> Callable[..., Awaitable[Any]]:
    """Return a traversal kernel for adapters that provide their own scoring."""

    canonical = canonical_search_method(name)
    try:
        return TRAVERSAL_METHODS[canonical]
    except KeyError as exc:
        choices = ", ".join(sorted(TRAVERSAL_METHODS))
        raise ValueError(
            f"Search method {canonical!r} has no standalone traversal kernel; choose one of: {choices}"
        ) from exc


async def run_search_method(name: str, engine: SearchEngine[StateT], **kwargs: Any) -> StateT | None:
    """Resolve and execute one proposal-search method."""

    method = get_search_method(name)
    return await method(engine, **kwargs)


def estimate_generated(breadth: int, depth: int, beam_width: int, method: str) -> int:
    """Estimate proposal states generated by a traversal topology."""

    canonical = canonical_search_method(method)
    if canonical == "single_turn":
        return max(1, int(breadth))
    if canonical in {"best_of_n", "mcts"}:
        return max(1, int(breadth)) * max(1, int(depth))
    if canonical == "tree_search":
        return estimate_tree_generated(breadth, depth)
    return estimate_beam_generated(breadth, depth, beam_width)


__all__ = [
    "SEARCH_METHOD_ALIASES",
    "SEARCH_METHODS",
    "TRAVERSAL_METHODS",
    "SearchEngine",
    "SearchState",
    "SearchTraversalResult",
    "StateT",
    "beam_search",
    "best_of_n",
    "canonical_search_method",
    "estimate_beam_generated",
    "estimate_generated",
    "estimate_tree_generated",
    "get_search_method",
    "get_traversal_method",
    "mcts",
    "run_search_method",
    "single_turn",
    "traverse_beam_search",
    "traverse_best_of_n",
    "traverse_single_turn",
    "traverse_tree_search",
    "tree_search",
]

