"""Task-neutral contracts for proposal-state search methods."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Generic, Iterable, Protocol, TypeVar


class SearchState(Protocol):
    """Minimum state shape required by the shared traversal algorithms."""

    depth: int
    score: float | None


StateT = TypeVar("StateT", bound=SearchState)


class SearchEngine(Protocol, Generic[StateT]):
    """Adapter implemented by a task or scoring layer that searches states."""

    evaluation_count: int

    @property
    def evaluation_interval(self) -> int: ...

    def create_seed_state(self) -> StateT: ...

    async def expand_state(
        self,
        parent: StateT,
        count: int,
        *,
        search_note: str = "",
    ) -> list[StateT]: ...

    async def evaluate_many(self, states: Iterable[StateT]) -> None: ...

    async def defer_evaluation_many(
        self,
        states: Iterable[StateT],
        *,
        reason: str,
    ) -> None: ...

    def should_evaluate_depth(self, depth: int, max_depth: int | None = None) -> bool: ...

    def ranked_states(self, states: Iterable[StateT] | None = None) -> list[StateT]: ...

    def best_state(self, states: Iterable[StateT] | None = None) -> StateT | None: ...

    def reward(self, state: StateT) -> float: ...

    def start_progress(self, total: int, *, label: str) -> None: ...

    def finish_progress(self) -> None: ...


@dataclass(frozen=True)
class SearchTraversalResult(Generic[StateT]):
    """States generated by one proposal-search traversal."""

    generated: tuple[StateT, ...]
    leaves: tuple[StateT, ...]

